language: generic
#deprecated
#sudo: required
services:
  - docker
before_install: 
  - docker build -t vadimyershov/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vadimyershov/docker-react npm run test